BRANDS = {
    'google.com': 'google',
    'youtube.com': 'google',
    'gmail.com': 'google',
    'facebook.com': 'facebook',
    'instagram.com': 'facebook',
    'web.whatsapp.com': 'facebook',
    'amazon.com': 'amazon',
    'apple.com': 'apple',
    'yahoo.com': 'yahoo',
    'microsoft.com': 'microsoft',
    'hotmail.com': 'microsoft',
    'outlook.com': 'microsoft',
    'onedrive.com': 'microsoft',
}
